apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app-container
        image: zarardev/rails_docker_compose_psql_demo-web:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgres://dean:password123@db:5432/videodb_production"
        - name: RAILS_ENV
          value: "development"    
