apiVersion: v1
kind: Service
metadata:
  name: rails-service
spec:
  type: NodePort
  selector:
    app: rails-app
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
    nodePort: 31000
